### ISSUE TITLE
Markdown formatting issues

### ISSUE THREAD

**Issue by tradzik** [fossasia/fossasia11#10]
Hi,
there are some errors in markdown formatting.
1. Location post

http://imgur.com/i9uMjKT,5qSwyhS#0

http://imgur.com/i9uMjKT,5qSwyhS#1
1. Schedule

http://imgur.com/djpgZ9C

There might be also other mistakes. I suggest you to recheck that

**Comment by samarsault** [comment]
http://fossasia.github.io/fossasia11/2011/11/13/Location.html
http://fossasia.github.io/fossasia11/2011/11/13/Schedule.html

Works fine, fixed some markdown errors.
It doesn't appear on github well because they use different versions of markdown and the images have to do something with the baseurl

**Comment by samarsault** [comment]
@ty221 @RoonyH maybe we close this ??
