### ISSUE TITLE
Implement header menus as in original site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#18]

**Comment by samarsault** [comment]
@mariobehling, in the fossasia11 site, one menu is on the top-right and one is the main, should I create a top-right menu too ??

**Comment by mariobehling** [comment]
yes, please

**Comment by samarsault** [comment]
@mariobehling maybe we could have an alternate solution, a top-right menu doesn't look so good I guess. maybe all links in the menu and the mailing-list link in the footer ?

**Comment by mariobehling** [comment]
How about we try to try out some ideas:
a) move all items in the menu "posts" to main menu
b) rename the item "posts" to FOSSASIA Events
c) add FOSSASIA 2010, FOSSASIA 2012, FOSSASIA 2014, FOSSASIA 2015  below expandable menu item "FOSSASIA Events" -> compare to http://fossasia.org site

**Comment by samarsault** [comment]
@mariobehling, do we show the Wrap-Up link in the menu ?
The original site doesn't do this

**Comment by mariobehling** [comment]
no need, cause the logo directs to the start page with the wrap up.
As we dont have two menus here as the original site, we should look for another way to have a logic menu. "Posts" is not logic, cause this is not a blog for example. 

Also the event is over and we can provide links to previous and follow up events. Do you understand my previous comment?

**Comment by samarsault** [comment]
@mariobehling fixed https://github.com/fossasia/fossasia11/pull/40
