### ISSUE TITLE
Implement order of sidebars as in original site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#20]

**Comment by samarsault** [comment]
@mariobehling, should I add the facebook page widget to the bottom and also a flickr images section ?

**Comment by mariobehling** [comment]
Yes, please. Also take care to choose the right flickr tag (same as on original website)

**Comment by samarsault** [comment]
@mariobehling facebook below - https://github.com/samarjeet27/fossasia11/commit/92c03c2cc208dca44a072f22bf6eea8491e8874d
Also, I can't access http://2011.fossasia.org maybe you took it down ? Where can I get the flickr tags ??

**Comment by samarsault** [comment]
OK, added  Flickr images section https://github.com/samarjeet27/fossasia11/commit/a241e6a2b6420bf2168e89242ef840e87a4834f9

**Comment by mariobehling** [comment]
Some links seem to be missing e.g. Hotel Xoai

**Comment by samarjeet27** [comment]
Fixed https://github.com/samarjeet27/fossasia11/commit/398efaf7b759f857af3fa042ea138e0e6167b25f

**Comment by samarsault** [comment]
Fixed https://github.com/samarjeet27/fossasia11/commit/398efaf7b759f857af3fa042ea138e0e6167b25f
@mariobehling

**Comment by mariobehling** [comment]
Please center Logos that are smaller than the width area. Also center project logo columns. Cheers

**Comment by samarsault** [comment]
OK, fixed https://github.com/fossasia/fossasia11/pull/41

**Comment by mariobehling** [comment]
Does not look centered to me. Examples:
![screenshot from 2015-01-13 15 52 00](https://cloud.githubusercontent.com/assets/1583873/5722405/2b7389ba-9b3c-11e4-81c4-13d77e0b5120.png)
![screenshot from 2015-01-13 15 51 45](https://cloud.githubusercontent.com/assets/1583873/5722406/2b7a35d0-9b3c-11e4-90c3-1732f8c6ec57.png)

**Comment by samarsault** [comment]
@mariobehling done https://github.com/fossasia/fossasia11/pull/45
