### ISSUE TITLE
Please add colored background to some table rows on schedule

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#23]
Please add colored background to some table rows 
http://2011.fossasia.org/schedule
Maybe with scroll over effect?

**Comment by samarsault** [comment]
Done https://github.com/samarjeet27/fossasia11/commit/0739599f889621977a42d44d54d8e33b91e566a8

With hover effect

**Comment by samarsault** [comment]
@mariobehling can this be closed ?

**Comment by mariobehling** [comment]
Nice overscroll effect!

Can we also add the blueish and yellowish colors back to the small tables to make this a bit more colorful?

**Comment by mariobehling** [comment]
see here http://fossasia.github.io/fossasia11/schedule/

**Comment by samarsault** [comment]
@mariobehling, added the yellowish and blueish colors
https://github.com/samarjeet27/fossasia11/commit/21d0c1f8cdefcc6d872d2bf9240b30e1d5c18e01

**Comment by mariobehling** [comment]
Sorry, for confusion, but there is sometimes a logic in tables:
Please have a look here: http://2011.fossasia.org/location
This is according to precipitation for example. In the copy it is just in two colors now:
http://fossasia.github.io/fossasia11/location/

Yes, there are different tables:
Let's have a look here: http://2011.fossasia.org/schedule
Scrool to Schedule, Saturday Nov. 12
As you see here "some content goes over three rows"
Now you also added color here in this specific table and it is a bit confusing: http://fossasia.github.io/fossasia11/schedule/
So, please take care, that we have different table layouts for a reason.
So, I just three different layouts here, but big Internet services might have much more differences even if they are small on the first eye. 
Hope you find this look for detail helpful.

**Comment by samarsault** [comment]
@mariobehling, so I need the colored weather table isn't it or leave it white ?

**Comment by samarsault** [comment]
@mariobehling  https://github.com/samarjeet27/fossasia11/commit/9feafdfa78756106e33e4b79e837a05ce7720615

**Comment by samarsault** [comment]
@mariobehling can this be closed now ??
