### ISSUE TITLE
Spelling of words in "Capital" should be kept

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#24]
Not sure why and how this happened, but some words changed from capital to small on some pages, e.g.
http://2011.fossasia.org/schedule
Operating Systems and Applications
->
http://samarjeet27.github.io/fossasia11/2011/11/13/Schedule.html
Operating systems and Applications

As a track name it should be capital. This is just an example. Other places also changed. Please try to avoid those changes.

Nevertheless, there are probably typos somewhere. Maybe we can take care of those?

**Comment by samarsault** [comment]
@mariobehling most were "Operating System" only just one in Track 3, also the 2011.fossasia.org website is showing 503
https://github.com/samarjeet27/fossasia11/commit/8b813698e52f2082febb4ddaa28aa08828a1e5c9

**Comment by mariobehling** [comment]
we have server issues with the old site. this is one reason why we want to move the old sites to github. please use httrack to make a backup as html

**Comment by samarsault** [comment]
@mariobehling can't find any other typo ? can this be closed ?

**Comment by mariobehling** [comment]
I was wondering where the error came from. It takes a lot of time for me to go through all text and verify it. If you could tell why the changes happened, you could be sure, that no other text was changed. Any idea?

**Comment by samarsault** [comment]
@mariobehling I only wrote the tables by hand, rest all was generated by a tool, and I re-checked the tables and it seems fine

**Comment by mariobehling** [comment]
ah ok. now i understand. then let's close this issue
