### ISSUE TITLE
Change pages like fossasia11/about.html to fossasia11/about

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#25]
Also implement this for other pages

**Comment by samarsault** [comment]
@mariobehling fixed https://github.com/samarjeet27/fossasia11/commit/5090ee56a1bd60c186245006f6554673143aa0bb

**Comment by mariobehling** [comment]
pleae change it to lower case e.g. /about instead of /About.

**Comment by samarjeet27** [comment]
OK, @mariobehling changed to lower case in a series of commits
https://github.com/samarjeet27/fossasia11/commit/66de07d4c1c28b0145dd046c77b94ae9090d4bb8
https://github.com/samarjeet27/fossasia11/commit/034bbcabb92c3f462c46c82e1c6cee95c6487e43
https://github.com/samarjeet27/fossasia11/commit/6295c53fa29221aa12d962406fe11a0932ed4075

**Comment by samarsault** [comment]
@mariobehling fixed  in a series of commits
https://github.com/samarjeet27/fossasia11/commit/66de07d4c1c28b0145dd046c77b94ae9090d4bb8
https://github.com/samarjeet27/fossasia11/commit/034bbcabb92c3f462c46c82e1c6cee95c6487e43
https://github.com/samarjeet27/fossasia11/commit/6295c53fa29221aa12d962406fe11a0932ed4075
