### ISSUE TITLE
Substitute previous scaled down pictures with larger version from new "originals folder"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#32]
Please check, that pictures are not too big and reduce resolution. Can this be done automatically maybe? Please research solution e.g. with JS and document changes here as a comment.

**Comment by samarsault** [comment]
Maybe mobiles could be taken care of in a separate task ??

**Comment by mariobehling** [comment]
This is not mainly regarding mobiles. This task is about having bigger pictures, that fill the whole area not just the width of 700 pixels.

You can use larger pictures from the folder "originals", adapt them and put them in the img folder. Keep the original images for our reference in the "originals" folder.

**Comment by mariobehling** [comment]
![screenshot from 2015-01-12 18 54 47](https://cloud.githubusercontent.com/assets/1583873/5707942/3ab4954a-9a8d-11e4-9e95-656153e53835.png)

**Comment by samarsault** [comment]
@mariobehling, have an alternative solution, don't see any decrease in resolution as such.
https://github.com/fossasia/fossasia11/pull/46
