### ISSUE TITLE
Make page more responsive for small screens and mobiles

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#33]
- Is it possible to move the sites bar down automatically when we have small screens?

**Comment by samarsault** [comment]
@mariobehling sites bar ?

**Comment by samarsault** [comment]
@mariobehling 
![screen shot 2015-01-14 at 5 43 26 pm](https://cloud.githubusercontent.com/assets/2987087/5738666/e2958d86-9c14-11e4-968a-6ece54de643d.png)
the menu already has a mobile version

**Comment by mariobehling** [comment]
Great menu button! However:
1) Sidebar content is missing (it could flow below main area for example)
2) I also see in your screenshot, that the top area is smaller in width than the area below.

**Comment by samarsault** [comment]
@mariobehling fixed https://github.com/fossasia/fossasia11/pull/49
