### ISSUE TITLE
Expand FB and Flickr area to complete available area width

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#34]

**Comment by samarsault** [comment]
@mariobehling that's how it's in the FOSSASIA 2011 site, do we really need to change it ?
![screen shot 2015-01-11 at 12 18 33 pm](https://cloud.githubusercontent.com/assets/2987087/5694550/07e46e1c-998c-11e4-9832-282b03d7e145.png)

Also, in pages like contact where page height < sidebar-height , it will collide with the sidebar.

**Comment by mariobehling** [comment]
Yes, we don't have to stick to the original page. The page was done a long time ago and web design has moved on. So little improvements would be nice. We are giving away space on the right hand side, without reason.

Regarding contact page, it would be nice if the bottom area would actually move down instead of overlapping with the sidebar.

**Comment by mariobehling** [comment]
Can we just make a new section maybe, so the sidebar does not overlap?

**Comment by samarsault** [comment]
@mariobehling https://github.com/fossasia/fossasia11/pull/41

**Comment by samarsault** [comment]
@mariobehling is it fine ?
