### ISSUE TITLE
Ensure that "Current Page" is highlighted in menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#42]
Usually, the currently selected page is highlighte in the menu. In this one "home" is always highlighted. Any idea?
![screenshot from 2015-01-12 19 04 21](https://cloud.githubusercontent.com/assets/1583873/5708034/fc701254-9a8d-11e4-8c81-b580cc336443.png)

**Comment by samarsault** [comment]
@mariobehling, done https://github.com/fossasia/fossasia11/pull/45
