### ISSUE TITLE
Expand Google map and pictures to complete width of available area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#43]
![screenshot from 2015-01-12 19 04 21](https://cloud.githubusercontent.com/assets/1583873/5708050/1bfe5c48-9a8e-11e4-9ade-abdbe72eec2a.png)

Google maps can be changed to 100% width of the available area in the code. Please try if this works here.

**Comment by samarsault** [comment]
@mariobehling fixed https://github.com/fossasia/fossasia11/pull/45
