### ISSUE TITLE
In small screen resolution, some areas behave and scale differently

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#44]
Please see at the pics. It is understandable what is the cause. How can we solve this?

![screenshot from 2015-01-12 19 09 45](https://cloud.githubusercontent.com/assets/1583873/5708129/cb0a616e-9a8e-11e4-823c-75c4a8ac60a7.png)

![screenshot from 2015-01-12 19 10 14](https://cloud.githubusercontent.com/assets/1583873/5708132/cfd6e780-9a8e-11e4-9f60-93dc3bbec8a2.png)

**Comment by samarsault** [comment]
@mariobehling fixed 
https://github.com/fossasia/fossasia11/issues/47
https://github.com/fossasia/fossasia11/pull/46

**Comment by mariobehling** [comment]
Table overflow in small screens
![screenshot from 2015-01-14 13 06 24](https://cloud.githubusercontent.com/assets/1583873/5738587/53d2f1e0-9bee-11e4-98b8-d265262eb258.png)

**Comment by samarsault** [comment]
@mariobehling  Fixed https://github.com/fossasia/fossasia11/pull/49
