### ISSUE TITLE
Fix footer in Firefox on smaller screens

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#50]
![screenshot from 2015-01-14 12 34 22](https://cloud.githubusercontent.com/assets/1583873/5739551/fb43594a-9bfa-11e4-98e4-47c5b0b1b28f.png)

**Comment by samarsault** [comment]
@mariobehling Fixed https://github.com/fossasia/fossasia11/pull/52

**Comment by samarsault** [comment]
@mariobehling, should this be closed ?
