### ISSUE TITLE
Fix footer to include licensing data on the right bottom: _includes/footer.html

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia11#75]
I just added the licensing code. Please help to fix the design.

**Comment by samarsault** [comment]
@mariobehling, maybe we should include only one, either the image or the text. what do you say ?

**Comment by mariobehling** [comment]
the whole thing needs to be included. you can make it on two lines.

**Comment by samarsault** [comment]
Fixed https://github.com/fossasia/fossasia11/pull/77

**Comment by mariobehling** [comment]
Link to Creative Commons license page is not clickable

**Comment by samarsault** [comment]
@mariobehling, Fixed https://github.com/fossasia/fossasia11/pull/79
